application: baseapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /images
  static_dir: images
 
- url: /javascripts
  static_dir: javascripts   

- url: /html
  static_dir: html

- url: /.*
  script: app.py

